# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.22.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.22.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arthurb/www/facul_ed2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arthurb/www/facul_ed2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.22.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.22.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.22.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arthurb/www/facul_ed2/CMakeFiles /Users/arthurb/www/facul_ed2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arthurb/www/facul_ed2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tree

# Build rule for target.
tree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree
.PHONY : tree

# fast build rule for target.
tree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/build
.PHONY : tree/fast

#=============================================================================
# Target rules for targets named student

# Build rule for target.
student: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 student
.PHONY : student

# fast build rule for target.
student/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/build
.PHONY : student/fast

#=============================================================================
# Target rules for targets named trees

# Build rule for target.
trees: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trees
.PHONY : trees

# fast build rule for target.
trees/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.dir/build.make CMakeFiles/trees.dir/build
.PHONY : trees/fast

#=============================================================================
# Target rules for targets named bst_test

# Build rule for target.
bst_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bst_test
.PHONY : bst_test

# fast build rule for target.
bst_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bst_test.dir/build.make CMakeFiles/bst_test.dir/build
.PHONY : bst_test/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/Experimental.dir/build.make _deps/check-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/Nightly.dir/build.make _deps/check-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/Continuous.dir/build.make _deps/check-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/check-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlyStart.dir/build.make _deps/check-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/check-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/check-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlyBuild.dir/build.make _deps/check-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlyTest.dir/build.make _deps/check-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/check-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/check-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/NightlySubmit.dir/build.make _deps/check-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/check-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/check-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/check-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/check-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/check-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/check-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/check-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/check-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ContinuousStart.dir/build.make _deps/check-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/check-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/check-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/check-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ContinuousTest.dir/build.make _deps/check-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/check-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/check-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/check-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named compat

# Build rule for target.
compat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compat
.PHONY : compat

# fast build rule for target.
compat/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/lib/CMakeFiles/compat.dir/build.make _deps/check-build/lib/CMakeFiles/compat.dir/build
.PHONY : compat/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/src/CMakeFiles/check.dir/build.make _deps/check-build/src/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named checkShared

# Build rule for target.
checkShared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 checkShared
.PHONY : checkShared

# fast build rule for target.
checkShared/fast:
	$(MAKE) $(MAKESILENT) -f _deps/check-build/src/CMakeFiles/checkShared.dir/build.make _deps/check-build/src/CMakeFiles/checkShared.dir/build
.PHONY : checkShared/fast

src/bst/main.o: src/bst/main.c.o
.PHONY : src/bst/main.o

# target to build an object file
src/bst/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/bst/main.c.o
.PHONY : src/bst/main.c.o

src/bst/main.i: src/bst/main.c.i
.PHONY : src/bst/main.i

# target to preprocess a source file
src/bst/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/bst/main.c.i
.PHONY : src/bst/main.c.i

src/bst/main.s: src/bst/main.c.s
.PHONY : src/bst/main.s

# target to generate assembly for a file
src/bst/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/bst/main.c.s
.PHONY : src/bst/main.c.s

src/bst/tree.o: src/bst/tree.c.o
.PHONY : src/bst/tree.o

# target to build an object file
src/bst/tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/bst/tree.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.dir/build.make CMakeFiles/trees.dir/src/bst/tree.c.o
.PHONY : src/bst/tree.c.o

src/bst/tree.i: src/bst/tree.c.i
.PHONY : src/bst/tree.i

# target to preprocess a source file
src/bst/tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/bst/tree.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.dir/build.make CMakeFiles/trees.dir/src/bst/tree.c.i
.PHONY : src/bst/tree.c.i

src/bst/tree.s: src/bst/tree.c.s
.PHONY : src/bst/tree.s

# target to generate assembly for a file
src/bst/tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/bst/tree.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/trees.dir/build.make CMakeFiles/trees.dir/src/bst/tree.c.s
.PHONY : src/bst/tree.c.s

src/rev/main.o: src/rev/main.c.o
.PHONY : src/rev/main.o

# target to build an object file
src/rev/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/rev/main.c.o
.PHONY : src/rev/main.c.o

src/rev/main.i: src/rev/main.c.i
.PHONY : src/rev/main.i

# target to preprocess a source file
src/rev/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/rev/main.c.i
.PHONY : src/rev/main.c.i

src/rev/main.s: src/rev/main.c.s
.PHONY : src/rev/main.s

# target to generate assembly for a file
src/rev/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/rev/main.c.s
.PHONY : src/rev/main.c.s

src/rev/student.o: src/rev/student.c.o
.PHONY : src/rev/student.o

# target to build an object file
src/rev/student.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/rev/student.c.o
.PHONY : src/rev/student.c.o

src/rev/student.i: src/rev/student.c.i
.PHONY : src/rev/student.i

# target to preprocess a source file
src/rev/student.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/rev/student.c.i
.PHONY : src/rev/student.c.i

src/rev/student.s: src/rev/student.c.s
.PHONY : src/rev/student.s

# target to generate assembly for a file
src/rev/student.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student.dir/build.make CMakeFiles/student.dir/src/rev/student.c.s
.PHONY : src/rev/student.c.s

tests/bst_test.o: tests/bst_test.c.o
.PHONY : tests/bst_test.o

# target to build an object file
tests/bst_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bst_test.dir/build.make CMakeFiles/bst_test.dir/tests/bst_test.c.o
.PHONY : tests/bst_test.c.o

tests/bst_test.i: tests/bst_test.c.i
.PHONY : tests/bst_test.i

# target to preprocess a source file
tests/bst_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bst_test.dir/build.make CMakeFiles/bst_test.dir/tests/bst_test.c.i
.PHONY : tests/bst_test.c.i

tests/bst_test.s: tests/bst_test.c.s
.PHONY : tests/bst_test.s

# target to generate assembly for a file
tests/bst_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bst_test.dir/build.make CMakeFiles/bst_test.dir/tests/bst_test.c.s
.PHONY : tests/bst_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... bst_test"
	@echo "... check"
	@echo "... checkShared"
	@echo "... compat"
	@echo "... student"
	@echo "... tree"
	@echo "... trees"
	@echo "... src/bst/main.o"
	@echo "... src/bst/main.i"
	@echo "... src/bst/main.s"
	@echo "... src/bst/tree.o"
	@echo "... src/bst/tree.i"
	@echo "... src/bst/tree.s"
	@echo "... src/rev/main.o"
	@echo "... src/rev/main.i"
	@echo "... src/rev/main.s"
	@echo "... src/rev/student.o"
	@echo "... src/rev/student.i"
	@echo "... src/rev/student.s"
	@echo "... tests/bst_test.o"
	@echo "... tests/bst_test.i"
	@echo "... tests/bst_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

